name: Continuous Integration

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Clear NuGet cache
      run: nuget locals all -clear
    - name: Restore dependencies
      run: dotnet restore
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName!~TestSculptorTests.TraditionalDatabases"
    - name: Build and Pack
      run: dotnet pack --configuration Release --output ./out --verbosity detailed
    - name: Push to NuGet
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet nuget push ./out/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate