name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOTNET_VERSION: '8.0.x'
  CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Display directory structure
      shell: pwsh
      run: |
        Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse | Select-Object FullName
        Write-Output "Current directory: $PWD"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Run unit tests
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal --filter "FullyQualifiedName!~TestSculptorTests.TraditionalDatabases"

    - name: Pack
      shell: pwsh
      run: |
        New-Item -Path ./artifacts -ItemType Directory -Force
        dotnet pack --configuration ${{ env.CONFIGURATION }} --no-build --output ./artifacts

    - name: List artifacts
      shell: pwsh
      run: Get-ChildItem -Path ./artifacts -Recurse | Select-Object FullName

    - name: Push to NuGet
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate