name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOTNET_VERSION: '8.0.x'
  CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build solution
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Run unit tests
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal --filter "FullyQualifiedName!~TestSculptorTests.TraditionalDatabases"
    - name: Pack solution
      run: dotnet pack --configuration ${{ env.CONFIGURATION }} --no-build --output ./artifacts
    - name: Push to NuGet
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        $packages = Get-ChildItem -Path .\artifacts -Recurse -Filter *.nupkg
        if ($packages.Count -eq 0) {
          Write-Error "No .nupkg files found in artifacts directory"
          exit 1
        }
        foreach ($package in $packages) {
          Write-Host "Pushing package: $($package.FullName)"
          dotnet nuget push $package.FullName --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
          if ($lastexitcode -ne 0) {
            Write-Error "Failed to push package: $($package.FullName)"
            exit 1
          }
        }